### PR TITLE
nix: allow flake to be used with nix < 2.4

### PR DESCRIPTION
**Pull request by NotAShelf**
Partially addresses #91 by better supporting non-flake systems.

@fdev31 where would you like me to document Nix usage? Should it go under the wiki page, or is the README fine?

### CODE REVIEW

**Comment by fdev31** [comment]
You rock! :)
I was more thinking on the wiki but a link to it from the README seems a good idea, It would really great if you can write something!

**Comment by NotAShelf** [comment]
I'll draft something in the morning 👍🏻

**Comment by NotAShelf** [comment]
@fdev31 
[nix.md](https://github.com/hyprland-community/pyprland/files/15138024/nix.md)


This should do it for the instructions. I've realized that the nixpkgs derivation for pyprland doesn't reflect upon the quality of the program (the nixpkgs package is *horrendous*) and I'll be also updating it soon. Marking this as ready for review, should be good to go.

**Comment by fdev31** [comment]
Added the instructions, the "main" link to it is [here](https://github.com/hyprland-community/pyprland/wiki/Getting-started#installation) but I also added some (which may disappear with time) in the README.

I can't tell too much about the .nix file quality but the documentation is looking good, thank you again :)

**Pull request merged**
