### PR TITLE
Add option to specify extra paths for plugins

### PR DESCRIPTION
**Pull request by Jozhin-s-Bazhin**
Added an option in `pyprland.toml` that lets you specify extra paths that pypr will search in for plugin modules. 
```
[pyprland]
plugins = [ "somebuiltinplugin", "external:customplugin" ]
plugin_paths = [ "/path/to/custom/plugin/" ]
```
Also fixed a bug that would prevent adding custom plugins at all, even using the more manual methods like installing the plugin using `pip install -e .`. At line 96 there is a statement that checks whether the plugin is specified relatively, and if it isn't, imports the plugin from `pyprland.plugins`.
```
modname = name if "." in name else f"pyprland.plugins.{name}"
```
I added an option to prepend `external:` before the plugin name to explicitly import it from outside `pypland.plugins`. In the case that the statement is actually working as intended this won't break any existing configurations. 
I tested if it works with a single example but haven't written any tests or documentation yet because I wanted to check if this format looks good.

Edit: I also added the default Python .gitignore template so that stuff like pycache isn't tracked by git

### CODE REVIEW

**Comment by fdev31** [comment]
Nice !
Maybe "plugin_paths" should be "plugins_paths" ?
I'll check the code after my work day but the description sounds good :)

**Comment by fdev31** [comment]
> I'm not a native english speaker so I have no idea how it's written correctly, but when I asked chatgpt it says "plugin_paths" is correct. I'm still not a native speaker, so if "plugins_paths" looks better to you I can add that :)

Oh, it's not about correctness, I believe both spellings are valid...(I'm also not a native speaker): it's more that we can load (several) "plugins", so when adding paths for it we should keep the same spelling as the "plugins" array... that's my only point ^^ 
So in short it's to be aligned with the existing variable name...

**Comment by Jozhin-s-Bazhin** [comment]
Oh, in that case case you're right. I'm gonna adjust it when I get back to my computer.

**Review by fdev31 — APPROVED** [review]
Great, thanks!

**Pull request merged**
